{
 "title": "Dremio Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Dremio Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(cluster:node_cpu:ratio_rate5m)"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilisation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Limits",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Limits",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", namespace=\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Dremio Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Jobs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "max(irate(jobs_total{container=\"dremio-master-coordinator\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Num Jobs"
      },
      {
       "expr": "sum(irate(jobs_failed{container=\"dremio-master-coordinator\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Failed Jobs"
      }
     ]
    },
    {
     "title": "Active Reflections and Failed Reflections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "max by(pod) (reflections_active{pod=\"dremio-master-0\", namespace=\"$namespace\"})",
       "legendFormat": "Active Reflections"
      },
      {
       "expr": "sum by(pod) (reflections_failed{pod=\"dremio-master-0\", namespace=\"$namespace\"})",
       "legendFormat": "Failed Reflections"
      }
     ]
    }
   ]
  },
  {
   "title": "Dremio Coordinator JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Command Pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "max(jobs_command_pool_active_threads)",
       "legendFormat": "Command Pool Active Threads"
      },
      {
       "expr": "max(jobs_command_pool_queue_size)",
       "legendFormat": "Command Pool Queue Size"
      },
      {
       "expr": "max(jobs_command_pool_reacquire_queue_size)",
       "legendFormat": "Command Pool Reaquire Pool Size"
      }
     ]
    },
    {
     "title": "Coordinator - Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (memory_heap_used{container=\"dremio-master-coordinator\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max by(namespace) (memory_heap_max{container=\"dremio-master-coordinator\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "Max Heap"
      }
     ]
    },
    {
     "title": "Coordinator - Dremio Memory JVM Direct Current",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (dremio_memory_jvm_direct_current{container=\"dremio-master-coordinator\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Coordinator - Dremio Memory Direct Current",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (dremio_memory_direct_current{container=\"dremio-master-coordinator\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Coordinator - Buffer Pool Direct Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (buffer_pool_direct_used{container=\"dremio-master-coordinator\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Coordinator - Buffer Pool Direct Capacity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (buffer_pool_direct_capacity{container=\"dremio-master-coordinator\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dremio Coordinator Workload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by(pod) (irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-master-coordinator\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-master-coordinator\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Memory Usage (Working Set Bytes)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"dremio-master-coordinator\"})",
       "legendFormat": "RSS {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-master-coordinator\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-master-coordinator\", resource=\"memory\"})",
       "legendFormat": "limits"
      },
      {
       "expr": "max by(pod) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"dremio-master-coordinator\"})",
       "legendFormat": "WSS {{pod}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max by(pod) (irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"dremio-master-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max by(pod) (irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"dremio-master-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by(pod) (irate(container_network_receive_packets_dropped_total{namespace=\"$namespace\", pod=~\"dremio-master-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by(pod) (irate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\", pod=~\"dremio-master-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "IOPS(Reads+Writes)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container=\"dremio-master-coordinator\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_total{container=\"dremio-master-coordinator\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ThroughPut(Read+Write)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container=\"dremio-master-coordinator\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container=\"dremio-master-coordinator\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dremio Executor JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (RSS) - Pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"dremio-executor\"})",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-executor\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-executor\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Executor - Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (memory_heap_used{container=\"dremio-executor\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max by(namespace) (memory_heap_max{container=\"dremio-executor\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "Max Heap"
      }
     ]
    },
    {
     "title": "Executor - Dremio Memory JVM Direct Current",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (dremio_memory_jvm_direct_current{container=\"dremio-executor\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Executor - Dremio Memory Direct Current",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (dremio_memory_direct_current{container=\"dremio-executor\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Executor - Buffer Pool Direct Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (buffer_pool_direct_used{container=\"dremio-executor\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Executor - Buffer Pool Direct Capacity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (buffer_pool_direct_capacity{container=\"dremio-executor\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Active Fragments",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "max by(pod) (fragments_active{namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dremio Executor Workload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor Nodes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"dremio-executor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by(pod) (irate(process_cpu_seconds_total{namespace=\"$namespace\", container=\"dremio-executor\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-executor\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-executor\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"dremio-executor\"})",
       "legendFormat": "WSS {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-executor\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-executor\", resource=\"memory\"})",
       "legendFormat": "limits"
      },
      {
       "expr": "max by(pod) (container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"dremio-executor\"})",
       "legendFormat": "RSS {{pod}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max by(pod) (irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"dremio-executor-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max by(pod) (irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"dremio-executor-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by(pod) (irate(container_network_receive_packets_dropped_total{namespace=\"$namespace\", pod=~\"dremio-executor-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by(pod) (irate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\", pod=~\"dremio-executor-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "IOPS(Reads+Writes)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container=\"dremio-executor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_total{container=\"dremio-executor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ThroughPut(Read+Write)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container=\"dremio-executor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container=\"dremio-executor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes - Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Node - Pod Mapping",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "label_join(\r\n sum by(node, host_ip, pod, pod_ip) (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\"}),\r\n \"instance\",\":9100\",\"host_ip\", \"doesmotexist\")"
      }
     ]
    },
    {
     "title": "CPU Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by(instance) (instance:node_cpu_utilisation:rate5m{job=\"node-exporter\"}) != 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Saturation (Load1 per CPU)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by(instance) (instance:node_load1_per_cpu:ratio{job=\"node-exporter\"} != 0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by(instance) (instance:node_memory_utilisation:ratio{job=\"node-exporter\"} != 0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Saturation (Major Page Faults)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "rds" } },
     "targets": [
      {
       "expr": "max by(instance) (instance:node_vmstat_pgmajfault:rate5m{job=\"node-exporter\"}) != 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network Utilisation (Bytes Receive/Transmit)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max by(instance) (instance:node_network_receive_bytes_excluding_lo:rate5m{job=\"node-exporter\"}) != 0",
       "legendFormat": "Receive {{instance}}"
      },
      {
       "expr": "sum by(instance) (instance:node_network_transmit_bytes_excluding_lo:rate5m{job=\"node-exporter\"} != 0)",
       "legendFormat": "Transmit {{instance}}"
      }
     ]
    },
    {
     "title": "Network Saturation (Drops Receive/Transmit)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "instance:node_network_receive_drop_excluding_lo:rate5m{job=\"node-exporter\"} != 0",
       "legendFormat": "Receive {{instance}}"
      },
      {
       "expr": "instance:node_network_transmit_drop_excluding_lo:rate5m{job=\"node-exporter\"} != 0",
       "legendFormat": "Transmit {{instance}}"
      }
     ]
    },
    {
     "title": "Disk IO Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by(instance, device) (instance_device:node_disk_io_time_seconds:rate5m{job=\"node-exporter\"}) != 0",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO Saturation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by(instance, device) (instance_device:node_disk_io_time_weighted_seconds:rate5m{job=\"node-exporter\"}) != 0",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    },
    {
     "title": "IO Wait in %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(max by (instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Space Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(1 -\n  (\n   max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\"})\n   /\n   max without (mountpoint, fstype) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\"})\n  ) != 0\n)\n",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Sessions",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "global_sessions{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Local Sessions",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "local_sessions{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "open_file_descriptor_count{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Leader Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "leader_uptime{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{instance}} leader_uptime"
      }
     ]
    },
    {
     "title": "Quorum Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{instance}} leader_uptime"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by(pod) (irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"kubernetes-zookeeper\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"kubernetes-zookeeper\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"kubernetes-zookeeper\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Memory Usage (Working Set Bytes)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"kubernetes-zookeeper\"})",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"kubernetes-zookeeper\", resource=\"memory\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"kubernetes-zookeeper\", resource=\"memory\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max by(pod) (irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"zk-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max by(pod) (irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"zk-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by(pod) (irate(container_network_receive_packets_dropped_total{namespace=\"$namespace\", pod=~\"zk-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by(pod) (irate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\", pod=~\"zk-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "IOPS(Reads+Writes)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container=\"kubernetes-zookeeper\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_total{container=\"kubernetes-zookeeper\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ThroughPut(Read+Write)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container=\"kubernetes-zookeeper\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container=\"kubernetes-zookeeper\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ZNode Count Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(znode_count{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}[$__rate_interval])",
       "legendFormat": "{{pod}} znode_count_rate"
      },
      {
       "expr": "rate(ephemerals_count{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ephemerals_rate"
      }
     ]
    },
    {
     "title": "ZNode Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "znode_count{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{pod}} znode_count"
      },
      {
       "expr": "ephemerals_count{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{pod}} ephemerals"
      }
     ]
    },
    {
     "title": "Zookeeper Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "proposal_ack_creation_latency{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{pod}} proposal_ack_creation_latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "Num Alive Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "num_alive_connections{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM Memory Bytes Pool Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{pod}} pool:{{pool}}"
      }
     ]
    },
    {
     "title": "JVM Threads State",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_state{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}",
       "legendFormat": "{{pod}} state:{{state}}"
      }
     ]
    },
    {
     "title": "JVM Pause Time Ms",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(jvm_pause_time_ms_sum{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}[$__rate_interval])",
       "legendFormat": "{{pod}} jvm_pause_time_ms"
      }
     ]
    },
    {
     "title": "JVM GC Collection Seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", job=\"$namespace/zookeeper-pod-monitor\"}[$__rate_interval])",
       "legendFormat": "{{pod}} gc:{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}