---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: zookeeper-pod-monitor
spec:
  selector:
    matchLabels:
      app: zk
  podMetricsEndpoints:
    - path: /metrics
      interval: 5s
      port: prometheus